before:
  hooks:
    - go mod download

builds:
  - id: sidecred
    dir: ./cmd/sidecred
    binary: sidecred
    ldflags: -buildid= -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
  - id: sidecred-lambda
    dir: ./cmd/sidecred-lambda
    binary: sidecred-lambda
    ldflags: -buildid= -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary
    builds:
      - sidecred
      - sidecred-lambda

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
