version: "2"

env:
  TERM: screen-256color
  GO111MODULE: on

vars:
  BUILD_VERSION:
    sh: git describe --tags --candidates=1 --dirty

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests.
    cmds:
      - task: test-go

  build:
    desc: Build binaries.
    cmds:
      - task: go-generate
      - task: test-go
      - task: go-build
        vars: {BINARY: sidecred, OS: '{{OS}}', ARCH: '{{ARCH}}'}
      - task: go-build
        vars: {BINARY: sidecred-lambda, OS: 'darwin', ARCH: 'amd64'}

  e2e:
    desc: Run E2E test suite
    cmds:
      - task: test
      - go test -race -v ./... -tags=e2e

  go-generate:
    desc: Generate test fakes
    cmds:
    - go generate ./...

  go-build:
    cmds:
    - mkdir -p build
    - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o build/{{.BINARY}}-{{.OS}}-{{.ARCH}}{{exeExt}} -ldflags="-buildid= -s -w" -trimpath -v cmd/{{.BINARY}}/main.go
    env:
      CGO_ENABLED: '0'

  test-go:
    desc: Run tests for all Go code.
    silent: true
    cmds:
    - gofmt -s -l -w .
    - go vet -v ./...
    - go test -race -v ./...
