version: "2"

env:
  TERM: screen-256color
  GO111MODULE: on

vars:
  BUILD_VERSION:
    sh: git describe --tags --candidates=1 --dirty

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests.
    cmds:
      - task: go-test

  build:
    desc: Build binaries.
    cmds:
      - task: go-generate
      - task: go-test
      - goreleaser --snapshot --rm-dist

  e2e:
    desc: Run E2E test suite
    cmds:
      - task: test
      - go test -race -v ./... -tags=e2e

  go-generate:
    desc: Generate test fakes
    cmds:
    - go generate ./...

  go-test:
    desc: Run tests for all Go code.
    silent: true
    cmds:
    - gofmt -s -l -w .
    - go vet -v ./...
    - go test -race -v ./...
