// Code generated by counterfeiter. DO NOT EDIT.
package artifactoryfakes

import (
	"sync"

	"github.com/jfrog/jfrog-client-go/artifactory/services"
	"github.com/telia-oss/sidecred/provider/artifactory"
)

type FakeArtifactoryAPI struct {
	CreateTokenStub        func(services.CreateTokenParams) (services.CreateTokenResponseData, error)
	createTokenMutex       sync.RWMutex
	createTokenArgsForCall []struct {
		arg1 services.CreateTokenParams
	}
	createTokenReturns struct {
		result1 services.CreateTokenResponseData
		result2 error
	}
	createTokenReturnsOnCall map[int]struct {
		result1 services.CreateTokenResponseData
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeArtifactoryAPI) CreateToken(arg1 services.CreateTokenParams) (services.CreateTokenResponseData, error) {
	fake.createTokenMutex.Lock()
	ret, specificReturn := fake.createTokenReturnsOnCall[len(fake.createTokenArgsForCall)]
	fake.createTokenArgsForCall = append(fake.createTokenArgsForCall, struct {
		arg1 services.CreateTokenParams
	}{arg1})
	fake.recordInvocation("CreateToken", []interface{}{arg1})
	fake.createTokenMutex.Unlock()
	if fake.CreateTokenStub != nil {
		return fake.CreateTokenStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.createTokenReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeArtifactoryAPI) CreateTokenCallCount() int {
	fake.createTokenMutex.RLock()
	defer fake.createTokenMutex.RUnlock()
	return len(fake.createTokenArgsForCall)
}

func (fake *FakeArtifactoryAPI) CreateTokenCalls(stub func(services.CreateTokenParams) (services.CreateTokenResponseData, error)) {
	fake.createTokenMutex.Lock()
	defer fake.createTokenMutex.Unlock()
	fake.CreateTokenStub = stub
}

func (fake *FakeArtifactoryAPI) CreateTokenArgsForCall(i int) services.CreateTokenParams {
	fake.createTokenMutex.RLock()
	defer fake.createTokenMutex.RUnlock()
	argsForCall := fake.createTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeArtifactoryAPI) CreateTokenReturns(result1 services.CreateTokenResponseData, result2 error) {
	fake.createTokenMutex.Lock()
	defer fake.createTokenMutex.Unlock()
	fake.CreateTokenStub = nil
	fake.createTokenReturns = struct {
		result1 services.CreateTokenResponseData
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactoryAPI) CreateTokenReturnsOnCall(i int, result1 services.CreateTokenResponseData, result2 error) {
	fake.createTokenMutex.Lock()
	defer fake.createTokenMutex.Unlock()
	fake.CreateTokenStub = nil
	if fake.createTokenReturnsOnCall == nil {
		fake.createTokenReturnsOnCall = make(map[int]struct {
			result1 services.CreateTokenResponseData
			result2 error
		})
	}
	fake.createTokenReturnsOnCall[i] = struct {
		result1 services.CreateTokenResponseData
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactoryAPI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createTokenMutex.RLock()
	defer fake.createTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeArtifactoryAPI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ artifactory.ArtifactoryAPI = new(FakeArtifactoryAPI)
