// Code generated by counterfeiter. DO NOT EDIT.
package githubfakes

import (
	"context"
	"sync"

	githuba "github.com/google/go-github/v29/github"
	"github.com/telia-oss/sidecred/provider/github"
)

type FakeAppsAPI struct {
	CreateInstallationTokenStub        func(context.Context, int64, *githuba.InstallationTokenOptions) (*githuba.InstallationToken, *githuba.Response, error)
	createInstallationTokenMutex       sync.RWMutex
	createInstallationTokenArgsForCall []struct {
		arg1 context.Context
		arg2 int64
		arg3 *githuba.InstallationTokenOptions
	}
	createInstallationTokenReturns struct {
		result1 *githuba.InstallationToken
		result2 *githuba.Response
		result3 error
	}
	createInstallationTokenReturnsOnCall map[int]struct {
		result1 *githuba.InstallationToken
		result2 *githuba.Response
		result3 error
	}
	ListInstallationsStub        func(context.Context, *githuba.ListOptions) ([]*githuba.Installation, *githuba.Response, error)
	listInstallationsMutex       sync.RWMutex
	listInstallationsArgsForCall []struct {
		arg1 context.Context
		arg2 *githuba.ListOptions
	}
	listInstallationsReturns struct {
		result1 []*githuba.Installation
		result2 *githuba.Response
		result3 error
	}
	listInstallationsReturnsOnCall map[int]struct {
		result1 []*githuba.Installation
		result2 *githuba.Response
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAppsAPI) CreateInstallationToken(arg1 context.Context, arg2 int64, arg3 *githuba.InstallationTokenOptions) (*githuba.InstallationToken, *githuba.Response, error) {
	fake.createInstallationTokenMutex.Lock()
	ret, specificReturn := fake.createInstallationTokenReturnsOnCall[len(fake.createInstallationTokenArgsForCall)]
	fake.createInstallationTokenArgsForCall = append(fake.createInstallationTokenArgsForCall, struct {
		arg1 context.Context
		arg2 int64
		arg3 *githuba.InstallationTokenOptions
	}{arg1, arg2, arg3})
	fake.recordInvocation("CreateInstallationToken", []interface{}{arg1, arg2, arg3})
	fake.createInstallationTokenMutex.Unlock()
	if fake.CreateInstallationTokenStub != nil {
		return fake.CreateInstallationTokenStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.createInstallationTokenReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAppsAPI) CreateInstallationTokenCallCount() int {
	fake.createInstallationTokenMutex.RLock()
	defer fake.createInstallationTokenMutex.RUnlock()
	return len(fake.createInstallationTokenArgsForCall)
}

func (fake *FakeAppsAPI) CreateInstallationTokenCalls(stub func(context.Context, int64, *githuba.InstallationTokenOptions) (*githuba.InstallationToken, *githuba.Response, error)) {
	fake.createInstallationTokenMutex.Lock()
	defer fake.createInstallationTokenMutex.Unlock()
	fake.CreateInstallationTokenStub = stub
}

func (fake *FakeAppsAPI) CreateInstallationTokenArgsForCall(i int) (context.Context, int64, *githuba.InstallationTokenOptions) {
	fake.createInstallationTokenMutex.RLock()
	defer fake.createInstallationTokenMutex.RUnlock()
	argsForCall := fake.createInstallationTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAppsAPI) CreateInstallationTokenReturns(result1 *githuba.InstallationToken, result2 *githuba.Response, result3 error) {
	fake.createInstallationTokenMutex.Lock()
	defer fake.createInstallationTokenMutex.Unlock()
	fake.CreateInstallationTokenStub = nil
	fake.createInstallationTokenReturns = struct {
		result1 *githuba.InstallationToken
		result2 *githuba.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAppsAPI) CreateInstallationTokenReturnsOnCall(i int, result1 *githuba.InstallationToken, result2 *githuba.Response, result3 error) {
	fake.createInstallationTokenMutex.Lock()
	defer fake.createInstallationTokenMutex.Unlock()
	fake.CreateInstallationTokenStub = nil
	if fake.createInstallationTokenReturnsOnCall == nil {
		fake.createInstallationTokenReturnsOnCall = make(map[int]struct {
			result1 *githuba.InstallationToken
			result2 *githuba.Response
			result3 error
		})
	}
	fake.createInstallationTokenReturnsOnCall[i] = struct {
		result1 *githuba.InstallationToken
		result2 *githuba.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAppsAPI) ListInstallations(arg1 context.Context, arg2 *githuba.ListOptions) ([]*githuba.Installation, *githuba.Response, error) {
	fake.listInstallationsMutex.Lock()
	ret, specificReturn := fake.listInstallationsReturnsOnCall[len(fake.listInstallationsArgsForCall)]
	fake.listInstallationsArgsForCall = append(fake.listInstallationsArgsForCall, struct {
		arg1 context.Context
		arg2 *githuba.ListOptions
	}{arg1, arg2})
	fake.recordInvocation("ListInstallations", []interface{}{arg1, arg2})
	fake.listInstallationsMutex.Unlock()
	if fake.ListInstallationsStub != nil {
		return fake.ListInstallationsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.listInstallationsReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAppsAPI) ListInstallationsCallCount() int {
	fake.listInstallationsMutex.RLock()
	defer fake.listInstallationsMutex.RUnlock()
	return len(fake.listInstallationsArgsForCall)
}

func (fake *FakeAppsAPI) ListInstallationsCalls(stub func(context.Context, *githuba.ListOptions) ([]*githuba.Installation, *githuba.Response, error)) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = stub
}

func (fake *FakeAppsAPI) ListInstallationsArgsForCall(i int) (context.Context, *githuba.ListOptions) {
	fake.listInstallationsMutex.RLock()
	defer fake.listInstallationsMutex.RUnlock()
	argsForCall := fake.listInstallationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAppsAPI) ListInstallationsReturns(result1 []*githuba.Installation, result2 *githuba.Response, result3 error) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = nil
	fake.listInstallationsReturns = struct {
		result1 []*githuba.Installation
		result2 *githuba.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAppsAPI) ListInstallationsReturnsOnCall(i int, result1 []*githuba.Installation, result2 *githuba.Response, result3 error) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = nil
	if fake.listInstallationsReturnsOnCall == nil {
		fake.listInstallationsReturnsOnCall = make(map[int]struct {
			result1 []*githuba.Installation
			result2 *githuba.Response
			result3 error
		})
	}
	fake.listInstallationsReturnsOnCall[i] = struct {
		result1 []*githuba.Installation
		result2 *githuba.Response
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAppsAPI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createInstallationTokenMutex.RLock()
	defer fake.createInstallationTokenMutex.RUnlock()
	fake.listInstallationsMutex.RLock()
	defer fake.listInstallationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAppsAPI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ github.AppsAPI = new(FakeAppsAPI)
